### ISSUE TITLE
USER STORY: Recipe creation

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#1]
As a **Admin** I can **create a new recipe** so that **it can be shared on the website**

**Acceptance criteria**

- [x] Recipe form has title, slug, description, tag, image, ingredients, calories, macros
- [x] The Admin can add as many ingredients as needed
- [x] The Admin can choose between draft or published
- [x] The Admin can edit the recipe

**Tasks**

- [x] Task 1 : Design and implement new recipe item
- [x] Task 2: Test recipe creation/deletion functionality
