### ISSUE TITLE
USER STORY: Recipe details display

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#14]
As a **user** I can **click on a recipe ** so that **I can read the full recipe with details.**

**Acceptance criteria**

- [x]  When a recipe is clicked the user is redirected to a page with the recipe details
- [x] When logged in, the user can also see recipe likes and comments

**Tasks**

- [x] Task 1 : Implement recipe details page
- [x] Task 2: Test recipe details page to see that all details are displayed
