### ISSUE TITLE
USER STORY: Recipe number of likes

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#15]
As a **user** I can **view the number of likes on each recipe** so that **I can see which is the most popular.**

**Acceptance criteria**

- [x] Recipe likes are clearly indicated
- [x] Total like count is displayed

**Tasks**

- [x] Task 1 : Implement Likes model
- [x] Task 2: Add like icon and total count to template
- [x] Task 3: Test that counts are working
