### ISSUE TITLE
USER STORY: Recipe filtering

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#18]
As a **user** I can **click on a tag of a recipe and filter** so that **I can see only recipes with that tag**

**Acceptance criteria**

- [x] Tags are mandatory to add when creating a recipe
- [x] Tags clearly show what kind of category the recipe belongs to
- [x] When a tag is clicked all recipes with that tag are shown

**Tasks**

- [x] Task 1 : Make sure TaggebleManager is added to the Recipe model
- [x] Task 2: Test that the filtering works on Frontend
