### ISSUE TITLE
USER STORY: User Sign Up

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#19]
As a **role** I can **sign up for an account ** so that ** I can interact with site content.**

**Acceptance criteria**

- [x] Sign up page is easily accessed
- [x] Submission of sign up form creates the user account 
- [x] A message that the account was created is displayed
- [x] When the user is logged in they can comment on recipes

**Tasks**

- [ ] Task 1 : Install Allauth
- [x] Task 2 : style log in page
- [x] Task 3 : Provide link to sign up page
- [x] Task 4 : Test Sign up functionality
