### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#2]
As a **User** I can **get a clear understanding of the site purpose when accessing the home page** so that **I fully understand what it is about at first glance**

**Acceptance criteria**

- [x] Landing page has a hero image that gives a purpose to the page
- [x] There are quick links to recipes and sign in/register

**Tasks**

- [x]  Task 1: Create the hero section with UX in mind
- [x] Task 2: Test that the links are working
