### ISSUE TITLE
USER STORY: User Log In

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#20]
As a **role** I can **easily sign in to my account** so that **I can use the site features on return visits.**

**Acceptance criteria**

- [x] Sign in page is easily accessed
- [x] Submission of sign in form signs the user into their account
- [ ] A message that the user is logged in is displayed

**Tasks**

- [x] Task 1 :create link to log in page
- [x] Task 2 : style log in page
- [x] Task 3 : test log in functionality
