### ISSUE TITLE
USER STORY: User Log out

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#21]
As a **user** I can **easily log out of my account ** so that **I can keep my account secure.**

**Acceptance criteria**

- [x] Log out button is clearly shown
- [x] Log out page is clearly displayed when user clicks log out
- [x] A message that the user is logged out is displayed

**Tasks**

- [x] Task 1 : provide link to log out page
- [x] Task 2 : style log out page
