### ISSUE TITLE
USER STORY: User Contact Form

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#22]
As a **user** I can **fill in a contact form** so that **I can get in contact with the site owner**

**Acceptance criteria**

- [x] The contact form is clear and easy to fill in
- [x] All fields are validated
- [x] The form works and gives a confirmation when submitted

**Tasks**

- [ ] Task 1 : Create the form
- [x] Task 2 : make sure fields are validated according to content
- [x] Task 3 : Test the form validation and confirmation
