### ISSUE TITLE
USER STORY: About page

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#23]
As a **user** I can **read about the purpose of the site** so that **I get a better understanding of the services available**

**Acceptance criteria**

- [x] When the About link is clicked, the about text is visible.
- [ ] The information is clearly explaining the site purpose
- [x] The user gets a good understanding of what services are available
-

**Tasks**

- [ ] Task 1 : Set up about page in core app and wire up urls
- [x] Task 2: add about info
