### ISSUE TITLE
USER STORY: Recipe favourites

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#24]
As a **user** I can **like or unlike recipes** so that **received benefit**

**Acceptance criteria**

- [x] When clicking the heart on the recipe the count is incremented by one
- [x] When clicking an already clicked heart, the count is decremented by one
- [x] The recipes that are liked by the user is saved in a "favorites" display

**Tasks**

- [x] Task 1 : Implement Like-model
- [x] Task 2 : Design display of favorites
- [x] Task 2: Test recipe recipe favorite display
