### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#3]
As a **User** I can **use a simple navigation menu** so that **I can easily find content.**

**Acceptance criteria**

- [x] Navigation bar is clearly shown in the header of the page
- [x] Navigation bar is working and redirecting to the selected page

**Tasks**

- [x] Task 1: Create the navigation bar
- [x] Task 2: Test that the links are working
