### ISSUE TITLE
USER STORY: Site admin about page

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#30]
As a **site admin** I can **create or update the about page content** so that **it is available on the site.**

**Acceptance criteria**

- [x] The About app is visible in the admin panel
- [x] It is possible to create and update the about content

**Tasks**

- [x] Add about admin to admin.py file
