### ISSUE TITLE
USER STORY: Contact with clients

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#31]
As a **site owner** I can **get contact requests from users** so that **I am able to get new business and collaborations**

**Acceptance criteria**

- [x] Contact form can be filled in by the users
- [x] Posts is shown in the admin page
- [x] Posts can be marked as "read" in the admin page to show how many to process

**Tasks**

- [ ] Set up contact form
- [x] Test that messages are displayed in admin site
