### ISSUE TITLE
USER STORY: Navigation Responsiveness

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#4]
As a **user** I can **view the navigation menu on any screen sizes** so that **navigating the site remains easy on all my devices.**

**Acceptance criteria**

- [x] Navigation bar is changed and adjusted due to screen size
- [x] Navigation bar is working and redirecting to the selected page

**Tasks**

- [x] Task 1: Create the navigation bar for smaller screen sizes
- [x] Task 2: Test that the links are working
- [x] Task : Test that navbar is responsive
