### ISSUE TITLE
USER STORY: Social Media Links

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#5]
As a **user** I can **easily find social media links** so that **I can find and interact with a community of app users.**

**Acceptance criteria**

- [x] Social media icons are displayed in the footer of each page
- [ ] Social media links are working and, when clicked, redirecting to a new webpage

**Tasks**

- [ ] Task 1: Create the footer with the icons
- [x] Task 2: Test that the links are working
