### ISSUE TITLE
USER STORY: Recipe modification

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#6]
As a **admin** I can **update/edit my recipes ** so that **I can revise the recipe**

**Acceptance criteria**

- [x] Recipe can be updated
- [x] Date of update is shown

**Tasks**

- [x] Task 1 : Implement recipe update functionality
- [x] Task 2: Test recipe update functionality
