### ISSUE TITLE
USER STORY: Recipe deletion

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/fitness-recipes#7]
As a **role** I can **delete my recipes** so that **website is updated with relevant content**

**Acceptance criteria**

- [x] Recipe can be deleted

**Tasks**

- [x] Task 1 : Implement recipe delete functionality
- [x] Task 2: Test recipe delete functionality
